### ISSUE TITLE
i want to use it

### ISSUE THREAD

**Issue by livrasand** [josemh/SoundBoxRemote#6]
Hello, I would like to use the SoundBox API in my [Attendant Zoom](goattendant.com) application, a free app for meetings. Can you explain to me how I can use it?

**Comment by AntonyCorbett** [comment]
This API is used to control SoundBox software which is no longer maintained. SoundBox was discontinued some years ago and replaced with several discrete applications - OnlyM, OnlyT, and OnlyR.
